# Generated by Django 3.2.8 on 2021-11-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sno',
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
