# Generated by Django 3.2.8 on 2021-11-02 15:32

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20211102_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(default='SOME STRING'),
        ),
    ]
