# Generated by Django 3.2.8 on 2021-11-15 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_feedback_feedback_userfeedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
