# Generated by Django 3.2.8 on 2021-11-15 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
