# Generated by Django 3.2.8 on 2021-11-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='timeStamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
